import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { LandmarkIcon } from "lucide-react";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignUpButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import UserDropdown from "./user-dropdown";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <nav className="bg-primary p-8 text-white h-20 flex items-center justify-between">
            <Link
              href="/"
              className="text-2xl font-bold gap-2 flex items-center">
              <LandmarkIcon className="text-lime-500" />
              PinTrust
            </Link>
            <div>
              <SignedOut>
                <div className="flex items-center">
                  <Button
                    asChild
                    variant="link"
                    className="mr-4 text-white text-xl">
                    <SignInButton />
                  </Button>
                  <Button
                    asChild
                    variant="link"
                    className="mr-4 text-white text-xl">
                    <SignUpButton />
                  </Button>
                </div>
              </SignedOut>
              <SignedIn>
                <div className="flex items-center gap-4">
                  <UserDropdown />
                </div>
              </SignedIn>
            </div>
          </nav>
          {children}
          <Toaster position="bottom-right" />
        </body>
      </html>
    </ClerkProvider>
  );
}
